### ISSUE TITLE
Prodigal Error

### ISSUE THREAD

**Issue by thinkgenome** [Merck/deepbgc#28]
Error LOG part:
-------
== Prodigal Error: ================
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...

Error:  Sequence must be 20000 characters (only 10000 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
== End Prodigal Error. ============
-------

Will this (to run prodigal in meta mode) require some changes to source code or can be handled using deepbgc commandline?

**Comment by prihoda** [comment]
Hi @thinkgenome, thanks for this suggestion. We were thinking about adding this option, so since it looks like there is demand for it, I added it in DeepBGC version `0.1.16`, which is now available through `pip` and soon through `conda`. 

Now you can run `deepbgc prepare` and `deepbgc pipeline` with `--prodigal-meta-mode` option to run Prodigal in `-p meta` mode.

**Comment by thinkgenome** [comment]
Thanks again @prihoda
