### ISSUE TITLE
Replace hmmscan with hmmsearch?

### ISSUE THREAD

**Issue by danudwary** [Merck/deepbgc#36]
I suggested this in a closed issue discussion, but I'll post it as a request. The hmmscan portion of deepbgc takes a LONG time, and is computationally unnecessary, I believe, for what you're trying to do. This post from the hmmer author explains why. (It's a very old post, but I believe it still applies to hmmer 3.3)
https://cryptogenomicon.org/2011/05/27/hmmscan-vs-hmmsearch-speed-the-numerology/

Feel free to correct me if I'm wrong or misunderstanding the goal of that part of the pipeline.

**Comment by prihoda** [comment]
Hi @danudwary, this is a really good point. We also noticed that DeepBGC is taking up a **lot** of IO which is causing the long execution time. 

The issue is that the e-value we use to filter the Pfams is different between `hmmscan` and `hmmsearch`. The deep learning algorithm can be sensitive to these modifications that would change the input distribution of Pfams. I haven't had the time to look into a way to convert the e-values, is that something you could help with? 

Another solution would be to retrain the model, which would kill two birds with one stone since MIBiG 2.0 is out and our model is trained on MIBiG 1.4. But we would also have to make sure that users know about the `hmmscan` to `hmmsearch` change when they are using their custom models.

**Comment by danudwary** [comment]
I'm afraid I'm not terribly familiar with the math there, and how that effects evalues. I have a colleague who's very familiar with the hmmer code, though, so I'll see what I can learn. 

In the long run, if it just requires a model retraining, I think it's well worth it, personally. I have several thousand genomes I'd like to run on an HPC cluster, and reducing per-genome run time would be necessary. In my experience, hmmsearch parallelizes MUCH better, and I think you'd see the pipeline jobs complete within a few minutes, rather than hours.

**Comment by Microbiology** [comment]
Thanks for the input @danudwary and thanks for the extra info @prihoda!

As David said, @danudwary it would be really helpful if you could play around with it and let us know how it goes and if you find a solution that could be implemented. We would be more than happy to review a pull request as well, if that's alright. Unfortunately on our end, making this faster is not at the top of our list, although I do think it is valuable.

**Comment by danudwary** [comment]
I will withdraw this request! It turns out that we have a major I/O bottleneck on one of our filesystems that was slowing the hmmscan to a crawl. A test with hmmsearch showed similar results, and now I see that I can get around the slowdown by staging the deepbgc databases to on-node storage. I was also told that modern hmmscan should be similarly performant to hmmsearch. Apologies for jumping the gun here!

**Comment by prihoda** [comment]
@danudwary good to know, thanks
