### ISSUE TITLE
different number of elements in *.bgc.tsv rows

### ISSUE THREAD

**Issue by artur-matysik** [Merck/deepbgc#49]
Hi, 

recently I encounter the problem of different number of elements in the`*.bgc.tsv` output files. I am not sure if it is input specific or just result of the update to 1.25. For some rows, there seems to be missing `'\t'`s (`product_activity` variable), so the columns are shifted and can't be correctly imported as TSV. Attached is the output I got and the`.gbk` that produced the error.   

Thanks for having a look!
 
[deepBGC_issue.zip](https://github.com/Merck/deepbgc/files/6094614/deepBGC_issue.zip)

**Comment by prihoda** [comment]
Hi @artur-matysik, thanks for reporting again. This was caused by cluster annotations already being present (from antiSMASH), which was handled incorrectly in our TSV export function. You can `pip install deepbgc==0.1.26`. I also included some dependency changes that I had been wanting to fix for some time, so hopefully it didn't break anything.

**Comment by artur-matysik** [comment]
Works like a charm! 
Thanks @prihoda : )
